name: publish

on:
  push:
  workflow_dispatch:

jobs:
  package:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install NuGet CLI via Chocolatey
        shell: powershell
        run: choco install nuget.commandline -y

      - name: Add NuGet to PATH
        shell: powershell
        run: |
          $nugetPath = "${env:ChocolateyInstall}\bin"
          echo "$nugetPath" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

      - name: Create package
        shell: powershell
        run: nuget pack Hyjinx.Audio.OpenAL.Dependencies.nuspec -OutputDirectory ./out -Suffix "preview.${{ github.run_number }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./out/*.nupkg

  upload:
    runs-on: windows-latest
    if: github.event.action == 'published'

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/
          merge-multiple: true

      - name: Push package(s)
        shell: powershell
        run: nuget push dist/*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey "${{ secrets.NUGET_TOKEN }}"