name: publish

on:
  push:
  release:
    types: [ published ]

jobs:
  package:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up NuGet
        uses: nuget/setup-nuget@v2
        with:
          nuget-api-key: ${{ secrets.NUGET_TOKEN }}
          nuget-version: latest

      - name: Package preview
        if: github.event.action != 'published'
        shell: powershell
        run: nuget pack Hyjinx.OpenAL.native.nuspec -OutputDirectory ./out -Suffix "preview.${{ github.run_number }}"

      - name: Package release
        if: github.event.action == 'published'
        shell: powershell
        run: nuget pack Hyjinx.OpenAL.native.nuspec -OutputDirectory ./out

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: ./out/*.nupkg

  publish:
    runs-on: windows-latest
    needs: package

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: dist/

      - name: Set up NuGet
        uses: nuget/setup-nuget@v2
        with:
          nuget-api-key: ${{ secrets.NUGET_TOKEN }}
          nuget-version: latest

      - name: Push package(s)
        shell: powershell
        run: |
          Get-ChildItem -Path "dist" -Filter *.nupkg | ForEach-Object {
            Write-Host "Pushing $($_.FullName)"
            nuget push $_.FullName -Source https://api.nuget.org/v3/index.json
          }